config/routes.rb
require 'resque/server'

Rhsystem::Application.routes.draw do
  root to: 'static_pages#home'

  mount Resque::Server.new, at: '/resque'

  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'

  match 'schedules/change_schedule' => 'schedules#change_schedule', as: :change_schedule, via: :get

  match 'schedules/set_away/:id(.:format)' => 'schedules#set_away_status', as: :set_schedule_status, via: :get
  match 'schedules/set_open/:id(.:format)' => 'schedules#set_open_status', as: :set_schedule_open, via: :get
  match 'locations/get_city/:id(.:format)' => 'locations#get_city', as: :get_city, via: :get
  match 'schedules/table_preview' => 'schedules#table_preview', as: :get_schedule, via: :get

  match 'schedule_children/destroy/:id(.:format)' => 'schedule_children#destroy', as: :delete_event, via: :delete
  match 'schedule_children/destroy_one/:id(.:format)' => 'schedule_children#destroy_one', as: :delete_one_event, via: :delete

  get '/schedule_children/show_queue/:id(.:format)' => 'schedule_children#show_queue', as: :show_queue
  get '/schedules/fetch_calendar' => 'schedules#fetch_calendar', as: :fetch_calendar
  get '/schedules/fetch_pagination' => 'schedules#fetch_pagination', as: :fetch_pagination
  get '/schedules/fetch_stats' => 'schedules#fetch_stats', as: :fetch_stats
  get '/schedule_children/is_recurring' => 'schedule_children#is_recurring_event', as: :is_recurring

  concern :search_doctor do
    scope '/search', as: :search do
      get '/', to: 'users#search'
      get '/schedule/:id', to: 'schedule_children#doctor', as: :schedule
    end
  end

  # concerns :search_doctor

  devise_for :users, controllers: { registrations:  'registrations' }

  devise_scope :user do
    get 'signin', to: 'devise/sessions#new'
    delete 'signout', to: 'devise/sessions#destroy'
    get 'signup', to: 'devise/registrations#new'
    get 'reset', to: 'devise/passwords#new'
    get '/switch', to: 'users#switch'
    get '/queue/:id(.:format)', to: 'patient_queues#index', as: :queue
    delete '/queue', to: 'patient_queues#destroy'

    concerns :search_doctor
    scope :dashboard, as: :dashboard do
      get '/profile', to: 'users#profile'
      put '/profile/update_field', to: 'registrations#update_field'
      get '/settings', to: 'users#settings', as: :settings
      scope :settings, as: :settings do
        get '/edit(.:format)', to: 'registrations#edit', format: :json, as: :password
        put '/update(.:format)', to: 'registrations#update', as: :password_update
        get '/verifications', to: 'users#welcome'
        get '/verifications/location', to: 'locations#verification_locations'
        get '/verifications/stepone', to: 'users#verification_doctor'
      end

      # Doctor's menu
      get '/doctor', to: 'users#doctor_dashboard'
      get '/schedules', to: 'schedules#index'
      get '/schedules/new', to: 'schedules#new'
      post '/schedules/create', to: 'schedules#create'
      get '/event/:id(.:format)' => 'schedule_children#edit'
      match 'event/update/:id(.:format)' => 'schedule_children#update', via: :patch
      get '/schedule/:id', to: 'schedules#doctors_schedule', as: :schedule_data
      resources :locations, except: :show

      # Patient's menu
      get '/patient', to: 'users#patient_dashboard'
      scope :favorites, as: :favorites do
        get '/', to: 'favorites#index'
        post '/', to: 'favorites#create'
      end
      concerns :search_doctor
      scope :appointments, as: :appointments do
        get '/', to: 'patient_queues#appointments'
        post '/', to: 'patient_queues#create'
        get '/:id', to: 'patient_queues#show', as: :detail
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  before_create :set_default_role

  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  process_in_background :avatar, url_with_processing: false

  # Validations
  validates :name, presence: true
  validates :address, presence: true
  validates :phone, presence: true
  validates :email, presence: true
  validates :password, presence: true, on: :create
  validates :password, length: { minimum: 5, maximum: 120 }, on: :update, allow_blank: true
  validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/]

  enum role_types: [:doctor, :patient]

  ## Usage:
  ## u = User.last
  ## u.is? :doctor
  def is?(role)
    roles.include? User.role_types[role]
  end

  def valid_doctor?
    valid_doctor == true
  end

  def set_default_role
    set_role :patient unless roles.include? User.role_types[:patient]
  end

  def is_only_patient?
    is?(:patient) && roles.count == 1
  end

  def set_role(role)
    roles << User.role_types[role]
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  before_action :set_user, only: [:switch, :profile, :update, :settings, :upload_verification]
  before_action :update_doctor, only: [:verification_doctor]
  before_action :authenticate_user!, except: [:search]

  def switch
    @roles = current_user.roles
  end

  def doctor_dashboard
    session[:active_role] = :doctor
    redirect_to dashboard_profile_path
  end

  def patient_dashboard
    session[:active_role] = :patient
    redirect_to dashboard_profile_path
  end

  def settings
    redirect_to dashboard_settings_password_path
  end

  def welcome
    render 'users/verifications/welcome'
  end

  def verification_doctor
    render 'users/verifications/verification_doctor'
  end

  def upload_verification
  end

  # def get_fields
  #   render json: Field.select('id as value', 'name as text')
  # end

  def update
    respond_to do |format|
      if active_role? :doctor
        if @doctor.update(doctor_params)
          format.json { head :no_content }
        else
          format.json { head :no_content }
        end
      end
    end
  end

  def search
    @doctors = []
    if params[:keyword].present?
      @doctors = Doctor.search params[:keyword],
                               misspellings: { edit_distance: 3 },
                               page: params[:page],
                               per_page: 10,
                               limit: 100,
                               fields: [{ name: :word }, { name: :word_start }, { name: :word_middle }, { name: :word_end }, :code, :field_name]
    end

    respond_to do |format|
      format.html { render 'users/search/index' }
      format.js { render 'users/search/results' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
    @doctor = Doctor.find(current_user.id) if active_role? :doctor
  end

  def update_doctor
    @user = current_user
    @doctor = Doctor.new @user.attributes
  end

  def doctor_params
    # @json_params = ActionController::Parameters.new( JSON.parse(request.body.read) )
    params.require(:doctor).permit(:name, :address, :phone, :field_id, :description)
  end

  def user_params
    params.require(:user).permit(:name, :address, :phone)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def path_to_search
    ('/dashboard' if is_dashboard?).to_s + '/search'
  end

  def default_profile_info
    'users/shared/' + active_role.to_s + '_profile' unless active_role.nil?
  end
end

app/views/users/shared/_doctor_profile.html.haml
%table.table.table-user-information
  %tbody
    %tr
      %td
        %p
          %b#field= @doctor.field.name
    %tr
      %td{:id => "description", "data-type" => "textarea", "data-url" => "/dashboard/profile/update_field", "data-pk" => @user.id, "data-name" => "description"}= @doctor.description
      %td 
        %a#edit-description{:href => "#"}
          %i.fa.fa-pencil
    %tr
      %td
    %tr
      %td{:id => "address", "data-url" => "/dashboard/profile/update_field", "data-pk" => @user.id, "data-name" => "address"}= @doctor.address
      %td
        %a#edit-address{:href => "#"}
          %i.fa.fa-pencil
    %tr
      %td{:id => "phone", "data-url" => "/dashboard/profile/update_field", "data-pk" => @user.id, "data-name" => "phone"}= @doctor.phone
      %td
        %a#edit-phone{:href => "#"}
          %i.fa.fa-pencil

app/views/users/shared/_links.haml
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/users/shared/_patient_profile.html.haml
%table.table.table-user-information
  %tbody
    %tr
      %td{:id => "address", "data-url" => "/dashboard/profile/update_field", "data-pk" => @user.id, "data-name" => "address"}= @user.address
      %td
        %a#edit-address{:href => "#"}
          %i.fa.fa-pencil
    %tr
      %td{:id => "phone", "data-url" => "/dashboard/profile/update_field", "data-pk" => @user.id, "data-name" => "phone"}= @user.phone
      %td
        %a#edit-phone{:href => "#"}
          %i.fa.fa-pencil