config/routes.rb
require 'resque/server'

Rhsystem::Application.routes.draw do
  root to: 'static_pages#home'

  mount Resque::Server.new, at: '/resque'

  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'

  match 'schedules/change_schedule' => 'schedules#change_schedule', as: :change_schedule, via: :get

  match 'schedules/set_away/:id(.:format)' => 'schedules#set_away_status', as: :set_schedule_status, via: :get
  match 'schedules/set_open/:id(.:format)' => 'schedules#set_open_status', as: :set_schedule_open, via: :get
  match 'locations/get_city/:id(.:format)' => 'locations#get_city', as: :get_city, via: :get
  match 'schedules/table_preview' => 'schedules#table_preview', as: :get_schedule, via: :get

  match 'schedule_children/destroy/:id(.:format)' => 'schedule_children#destroy', as: :delete_event, via: :delete
  match 'schedule_children/destroy_one/:id(.:format)' => 'schedule_children#destroy_one', as: :delete_one_event, via: :delete

  get '/schedule_children/show_queue/:id(.:format)' => 'schedule_children#show_queue', as: :show_queue
  get '/schedules/fetch_calendar' => 'schedules#fetch_calendar', as: :fetch_calendar
  get '/schedules/fetch_pagination' => 'schedules#fetch_pagination', as: :fetch_pagination
  get '/schedules/fetch_stats' => 'schedules#fetch_stats', as: :fetch_stats
  get '/schedule_children/is_recurring' => 'schedule_children#is_recurring_event', as: :is_recurring

  concern :search_doctor do
    scope '/search', as: :search do
      get '/', to: 'users#search'
      get '/schedule/:id', to: 'schedule_children#doctor', as: :schedule
    end
  end

  # concerns :search_doctor

  devise_for :users, controllers: { registrations:  'registrations' }

  devise_scope :user do
    get 'signin', to: 'devise/sessions#new'
    delete 'signout', to: 'devise/sessions#destroy'
    get 'signup', to: 'devise/registrations#new'
    get 'reset', to: 'devise/passwords#new'
    get '/switch', to: 'users#switch'
    get '/queue/:id(.:format)', to: 'patient_queues#index', as: :queue
    delete '/queue', to: 'patient_queues#destroy'

    concerns :search_doctor
    scope :dashboard, as: :dashboard do
      get '/profile', to: 'users#profile'
      put '/profile/update_field', to: 'registrations#update_field'
      get '/settings', to: 'users#settings', as: :settings
      scope :settings, as: :settings do
        get '/edit(.:format)', to: 'registrations#edit', format: :json, as: :password
        put '/update(.:format)', to: 'registrations#update', as: :password_update
        get '/verifications', to: 'users#welcome'
        get '/verifications/location', to: 'locations#verification_locations'
        get '/verifications/stepone', to: 'users#verification_doctor'
      end

      # Doctor's menu
      get '/doctor', to: 'users#doctor_dashboard'
      get '/schedules', to: 'schedules#index'
      get '/schedules/new', to: 'schedules#new'
      post '/schedules/create', to: 'schedules#create'
      get '/event/:id(.:format)' => 'schedule_children#edit'
      match 'event/update/:id(.:format)' => 'schedule_children#update', via: :patch
      get '/schedule/:id', to: 'schedules#doctors_schedule', as: :schedule_data
      resources :locations, except: :show

      # Patient's menu
      get '/patient', to: 'users#patient_dashboard'
      scope :favorites, as: :favorites do
        get '/', to: 'favorites#index'
        post '/', to: 'favorites#create'
      end
      concerns :search_doctor
      scope :appointments, as: :appointments do
        get '/', to: 'patient_queues#appointments'
        post '/', to: 'patient_queues#create'
        get '/:id', to: 'patient_queues#show', as: :detail
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  before_create :set_default_role

  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  process_in_background :avatar, url_with_processing: false

  # Validations
  validates :name, presence: true
  validates :address, presence: true
  validates :phone, presence: true
  validates :email, presence: true
  validates :password, presence: true, on: :create
  validates :password, length: { minimum: 5, maximum: 120 }, on: :update, allow_blank: true
  validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/]

  enum role_types: [:doctor, :patient]

  ## Usage:
  ## u = User.last
  ## u.is? :doctor
  def is?(role)
    roles.include? User.role_types[role]
  end

  def valid_doctor?
    valid_doctor == true
  end

  def set_default_role
    set_role :patient unless roles.include? User.role_types[:patient]
  end

  def is_only_patient?
    is?(:patient) && roles.count == 1
  end

  def set_role(role)
    roles << User.role_types[role]
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  before_action :set_user, only: [:switch, :profile, :update, :settings, :upload_verification]
  before_action :update_doctor, only: [:verification_doctor]
  before_action :authenticate_user!, except: [:search]

  def switch
    @roles = current_user.roles
  end

  def doctor_dashboard
    session[:active_role] = :doctor
    redirect_to dashboard_profile_path
  end

  def patient_dashboard
    session[:active_role] = :patient
    redirect_to dashboard_profile_path
  end

  def settings
    redirect_to dashboard_settings_password_path
  end

  def welcome
    render 'users/verifications/welcome'
  end

  def verification_doctor
    render 'users/verifications/verification_doctor'
  end

  def upload_verification
  end

  # def get_fields
  #   render json: Field.select('id as value', 'name as text')
  # end

  def update
    respond_to do |format|
      if active_role? :doctor
        if @doctor.update(doctor_params)
          format.json { head :no_content }
        else
          format.json { head :no_content }
        end
      end
    end
  end

  def search
    @doctors = []
    if params[:keyword].present?
      @doctors = Doctor.search params[:keyword],
                               misspellings: { edit_distance: 3 },
                               page: params[:page],
                               per_page: 10,
                               limit: 100,
                               fields: [{ name: :word }, { name: :word_start }, { name: :word_middle }, { name: :word_end }, :code, :field_name]
    end

    respond_to do |format|
      format.html { render 'users/search/index' }
      format.js { render 'users/search/results' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
    @doctor = Doctor.find(current_user.id) if active_role? :doctor
  end

  def update_doctor
    @user = current_user
    @doctor = Doctor.new @user.attributes
  end

  def doctor_params
    # @json_params = ActionController::Parameters.new( JSON.parse(request.body.read) )
    params.require(:doctor).permit(:name, :address, :phone, :field_id, :description)
  end

  def user_params
    params.require(:user).permit(:name, :address, :phone)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def path_to_search
    ('/dashboard' if is_dashboard?).to_s + '/search'
  end

  def default_profile_info
    'users/shared/' + active_role.to_s + '_profile' unless active_role.nil?
  end
end

app/views/users/_form.html.haml
= form_for(@doctor) do |f|
  - if @doctor.errors.any?
    #error_explanation
      %h2
        = pluralize(@doctor.errors.count, "error")
        prohibited this doctor from being saved:
      %ul
        - @doctor.errors.full_messages.each do |msg|
          %li= msg
  .actions
    = f.submit

app/views/users/edit.html.haml
%h1 Editing doctor
= render 'form'
= link_to 'Show', @doctor
|
\#{link_to 'Back', doctors_path}

app/views/users/index.html.haml
%h1 Listing doctors
%table
  %thead
    %tr
      %th
      %th
      %th
  %tbody
    - @doctors.each do |doctor|
      %tr
        %td= link_to 'Show', doctor
        %td= link_to 'Edit', edit_doctor_path(doctor)
        %td= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Doctor', new_doctor_path

app/views/users/new.html.haml
%h1 New doctor
= render 'form'
= link_to 'Back', doctors_path

app/views/users/profile.html.haml
%p.lead Profil
.row
  .col-xs-12.col-sm-12.col-md-6.col-lg-6.col-xs-offset-0.col-sm-offset-0.toppad
    .panel.panel-info#profil-head
      .panel-heading
        .row
          .col-xs-10
            %h3.panel-title{:id => "name", "data-url" => "/dashboard/profile/update_field", "data-pk" => @user.id, "data-name" => "name"}= @user.name
          .col-xs-2
            %a#edit-name{:href => "#"}
              %i.fa.fa-pencil
      .panel-body
        .row
          .col-md-3.col-lg-3{:align => "center"}
            = image_tag current_user.avatar.url(:thumb)
          .col-md-9.col-lg-9#profile-detail
            = render :partial => default_profile_info

:coffee
$(document).ready ->
  
  #toggle `popup` / `inline` mode
  $.fn.editable.defaults.mode = "inline"
  $.fn.editable.defaults.ajaxOptions = {type: "PUT", dataType: 'json'}
  #make name editable
  $("#edit-name").click (e) ->
    $("#name").editable "enable"
    e.stopPropagation()
    $("#name").editable "toggle"
    $("#edit-name").hide()
    false


  $("#name").on "hidden", (e, reason) ->
    $("#name").editable "disable"
    $("#edit-name").show()
    false

  $("#edit-address").click (e) ->
    $("#address").editable "enable"
    e.stopPropagation()
    $("#address").editable "show"
    $("#edit-address").hide()
    false

  $("#address").on "hidden", (e, reason) ->
    $("#address").editable "disable"
    $("#edit-address").show()
    false

  $("#edit-phone").click (e) ->
    $("#phone").editable "enable"
    e.stopPropagation()
    $("#phone").editable "show"
    $("#edit-phone").hide()
    false

  $("#phone").on "hidden", (e, reason) ->
    $("#phone").editable "disable"
    $("#edit-phone").show()
    false

  $("#edit-description").click (e) ->
    $("#description").editable "enable"
    e.stopPropagation()
    $("#description").editable "show"
    $("#edit-description").hide()
    false

  $("#description").on "hidden", (e, reason) ->
    $("#description").editable "disable"
    e.stopPropagation()
    $("#edit-description").show()
    false
    
  
  return



                  
        

app/views/users/settings.html.haml
%h2
  Edit #{resource_name.to_s.humanize}
= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f|
  = devise_error_messages!
  = f.input :password, :autocomplete => "off"
  = f.input :password_confirmation
  = f.input :current_password
  = f.button :submit, "Update", input_html: { class: 'btn btn-primary' }

app/views/users/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_doctor_path(@doctor)
|
\#{link_to 'Back', doctors_path}

app/views/users/switch.html.haml
.well
  - if @roles.include? User.role_types[:doctor]
    = link_to t(:doctor), dashboard_doctor_path

  - if @roles.include? User.role_types[:patient]
    = link_to t(:patient), dashboard_patient_path